### ISSUE TITLE
puzzels sind da, gehören noch stimmig in die Szene eingebettet

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/4ahmns2122-VR-VRProjekt2122-smederer#7]

**Comment by smederer** [comment]
in meinem MVP werden die puzzels nur als Platzhalter/Objekt beschrieben....  Ich habe jetzt das ein oder andere verbessert, habe aber nicht für alles die Zeit gefunden. Ich denke dass passt trotzdem da im mvp keine rede von " stimmig in die Szene eingebetten" ist.
